name: Auto Video Creator

on:
  schedule:
    - cron: '0 */2 * * *' # يعمل تلقائياً كل ساعتين
  workflow_dispatch: # زر التشغيل اليدوي للتجربة

jobs:
  build:
    runs-on: ubuntu-latest
    
    # منح صلاحيات الكتابة لتحديث ملف الذاكرة (last_post.txt)
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # التحديث للإصدار الرابع

      - name: Set up Python
        uses: actions/setup-python@v5 # التحديث للإصدار الخامس
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg # تثبيت محرك الفيديو الأساسي

      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install feedparser edge-tts requests requests_toolbelt moviepy

      - name: Run automation script
        env:
          PEXELS_API: ${{ secrets.PEXELS_API }}
          DM_API_KEY: ${{ secrets.DM_API_KEY }}
          DM_API_SECRET: ${{ secrets.DM_API_SECRET }}
          DM_USER: ${{ secrets.DM_USER }}
          DM_PASS: ${{ secrets.DM_PASS }}
        run: python main.py

      - name: Commit and Push Last Post Update
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'action@github.com'
          git add last_post.txt
          git commit -m "Update last published post record" || exit 0
          git push
