name: YouTube Shorts Auto

on:
  schedule:
    - cron: '0 18 * * *' # الساعة 6 مساءً بتوقيت جرينتش (ذروة المشاهدة)
  workflow_dispatch: # للتشغيل اليدوي في أي وقت

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Libs
        run: pip install google-api-python-client google-auth-oauthlib groq feedparser moviepy edge_tts
      - name: Run Upload
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          PEXELS_API: ${{ secrets.PEXELS_API }}
        run: python youtube_worker.py
